In [1]:
import time
start_time = time.time()

import json
import pandas as pd
import numpy as np

In [ ]:
# Read all encrypted datasets into a list #
smallest = 0
dataset_list = []
for p in parties: 
    dataset_list.append(pd.read_csv('/data/encrypted_%s.csv' %(p)).set_index('encString'))

In [51]:
enc_1 = [[b'bae6fb057d8eb3d5d9154166075e7f4d675535be3544f32520f8e57707ff9cdd0d3e7957de8d6674318a666b347caa84eaf5b596b0a2483e9d6b57bdb3b30dab',2,3],
[b'776d7b46192d6b6872585a49eaa1239ee05b438d1704dd97de580c10207336ab0aa57749a52345f612a33b0e1550e4e2248ed87466de37fa338cd5f69a50abb9',2,3],
[b'e7d2e176a2ed495c83bb9ac109041f358dee6c95d36b6da298009174198424ade5b368615ff7ed8a468dda4da58899b3e44269cfbd6f69fc4a113fd1efeb4cb1',2,3]]

In [52]:
enc_2 = [[b'bae6fb057d8eb3d5d9154166075e7f4d675535be3544f32520f8e57707ff9cdd0d3e7957de8d6674318a666b347caa84eaf5b596b0a2483e9d6b57bdb3b30dab',2,3],
[b'776d7b46192d6b6872585a49eaa1239ee05b438d1704dd97de580c10207336ab0aa57749a52345f612a33b0e1550e4e2248ed87466de37fa338cd5f69a50abb9',2,3],
[b'e7d2e176a2ed495c83bb9ac109041f358dee6c95d36b6da298009174198424ade5b368615ff7ed8a468dda4da58899b3e44269cfbd6f69fc4a113fd1efeb4cb1',2,3],
[b'9ec0b3e1edfe87159a8e01bd0f21fec91a2e9777a61026d2a18f4a412b260b34b449922d640530919606ea54f32c9157bccee0100b8242f613bda42f94961cc4',2,3],
[b'4e55023b2e8e289e13d04b500d94f06b738b30658f04092c4f58bc63bf2729b6c1aa5253e890061b58a1d9ff2af1488caac21a384798e8fcd3c57dc1be51ad18',2,3],
[b'513261f65c0022ce2260c4fe70bfeb6e78a191f8f28cfa75b9cb6303188e20e4d348c161020a3df4f20295d44f6226c01b1a0a856d1f65fd0f2814a9981b86f3',2,3],
[b'a3bb81d7dd0ce099ca6560675c34918c9ebecc8eb4cfa6053f7d2b7338fc82bc7ba7f5ee9f50a262ce7367773c667a74e55359c9cde723b2d6d794a44cba6e2f',2,3],
[b'867d42ccb9758785b9acd8f4fac7100aefde24c22b65276d1909a13a28a176909f03f1f8d491646b0982ed754b28e3d75cbaf715295195fa826915e81be37611',2,3],
[b'4cd3cd731842c7328f0f6186c29892c4650f27cdd3ca620d774455688ee87806e2c90610934849fcd3001277934c91b6cff11a2fcb3ffdb3eb42b6f56010fd12',2,3],
[b'1bc5d8c0e5a8b764cf9b0d535b012f6a065e4c58a5041a0ccba26a8dc0cc6d9ba55c1da1e9e340e5d62a7e44fe0f64e60dc5416e543432d6f296b7da22829c41',2,3],
[b'c98b43baf75a15511e5a44425c19593b9e03a4211bbf9fea2cc8155f48b12f79610382888affc0fc04764913086fdbc8a27688623a30a7dcfc53e39fca374aef',2,3],
[b'dd6084fa715637bf9b8b671a70f97cd14b4af08b9247963a722236077f58a7b3ccc99d1d5ad4bfd51a22330577a0831c0926e64ad10b0c86335403e6a63dd597',2,3],
        [b'bae6fb057d8eb3d5d9154166075e7f4d675535be3544f32520f8e57707ff9cdd0d3e7957de8d6674318a666b347caa84eaf5b596b0a2483e9d6b57bdb3b30dab',2,3]]

In [67]:
df_1 = pd.DataFrame.from_records(enc_1, columns=['enc','a','b'], index='enc')
df_2 = pd.DataFrame.from_records(enc_2, columns=['enc','a','b'],index='enc')
print(df_1.dtypes)
df_1 = df_1.astype('float', copy=False)
print(df_1.dtypes)
# with open('bababaab.txt', 'w') as f:
#     f.write(str(df_1.dtypes))
#     for item in cmb_col:
#         f.write("%s\n" % item)

a    int64
b    int64
dtype: object
a    float64
b    float64
dtype: object

In [54]:
dataset_list=[df_2,df_1]

In [55]:
# Order the size of datasets from small to large #
sizes = []
for dataset in dataset_list:
    sizes.append(len(dataset))
order = np.argsort(sizes)
order
# Find match records #

array([1, 0])

In [58]:
for item in range(0, len(order)): 
    multi_match = []
    exact_match = []
    no_match = []
    if item == 0:
        combined_df = dataset_list[order[item]]
#         print(combined_df)
    else:
        for i in combined_df.index:
            try:
                pair = dataset_list[order[item]].loc[i]
                print(pair)
                if type(pair) == pd.DataFrame:
                    multi_match.append(i)
                elif type(pair) == pd.Series:
                    exact_match.append(i)
            except:
                no_match.append(i)

0
1
                                                    a  b
enc
b'bae6fb057d8eb3d5d9154166075e7f4d675535be3544f...  2  3
b'bae6fb057d8eb3d5d9154166075e7f4d675535be3544f...  2  3
a    2
b    3
Name: b'776d7b46192d6b6872585a49eaa1239ee05b438d1704dd97de580c10207336ab0aa57749a52345f612a33b0e1550e4e2248ed87466de37fa338cd5f69a50abb9', dtype: int64
a    2
b    3
Name: b'e7d2e176a2ed495c83bb9ac109041f358dee6c95d36b6da298009174198424ade5b368615ff7ed8a468dda4da58899b3e44269cfbd6f69fc4a113fd1efeb4cb1', dtype: int64

In [57]:
print(len(multi_match, exact_match,no_match)

[b'bae6fb057d8eb3d5d9154166075e7f4d675535be3544f32520f8e57707ff9cdd0d3e7957de8d6674318a666b347caa84eaf5b596b0a2483e9d6b57bdb3b30dab'] [b'776d7b46192d6b6872585a49eaa1239ee05b438d1704dd97de580c10207336ab0aa57749a52345f612a33b0e1550e4e2248ed87466de37fa338cd5f69a50abb9', b'e7d2e176a2ed495c83bb9ac109041f358dee6c95d36b6da298009174198424ade5b368615ff7ed8a468dda4da58899b3e44269cfbd6f69fc4a113fd1efeb4cb1'] []

In [69]:
import pandas as pd
df = pd.read_csv('20191030_query_result.csv')
col = df.columns
##### Search missing valves #####
missing  = 0
misVariables = []
CheckNull = df.isnull().sum()
for var in range(0, len(CheckNull)):
    if CheckNull[var] != 0:
        misVariables.append([col[var], CheckNull[var], round(CheckNull[var]/len(df),3)])
        missing = missing + 1

if missing == 0:
    print('Dataset is complete with no blanks.')
else:
    print('Totally, %d features have missing values (blanks).' %missing)
    df_misVariables = pd.DataFrame.from_records(misVariables)
    df_misVariables.columns = ['Variable', 'Missing', 'Percentage (%)']
    sort_table = df_misVariables.sort_values(by=['Percentage (%)'], ascending=False)
print('Missing values check is done!')

Totally, 30 features have missing values (blanks).
Missing values check is done!

In [76]:
# df.dtypes
# from collections import Counter
# Counter(df['med_depression'])

Counter({'no': 3041, 'yes': 242})

In [70]:
sort_table

                  Variable  Missing  Percentage (%)
0               N_DM_DUR_2     2524           0.769
6        Income_equivalent      807           0.246
25    MEAN_STEP_MIN_WAKE_T      778           0.237
24   MEAN_STAND_MIN_WAKE_T      778           0.237
23     MEAN_SED_MIN_WAKE_T      778           0.237
22  MEAN_VALID_MIN_SLEEP_T      763           0.232
5    Occupational_category      485           0.148
21                    MVPA      419           0.128
20                 TOTALPA      418           0.127
4        Employment_status      314           0.096
16               PHQ9_depr      276           0.084
18            MINIlifedepr      254           0.077
11           medGRscore_TR      215           0.065
10                NIT_kcal      214           0.065
17            MINIcurrdepr      133           0.041
8                      WOZ      108           0.033
28                 SF36_Q7       84           0.026
29                SF36_Q10       86           0.026
3         N_Education_3cat       70           0.021
15                   N_CVD       63           0.019
9            N_ALCOHOL_CAT       45           0.014
7            n_smokingcat4       47           0.014
1             N_DIABETES_2       39           0.012
2         N_T2DM_new_diagn       39           0.012
19                    N_HT        6           0.002
27                     hip        5           0.002
14                     bmi        3           0.001
13                  weight        2           0.001
12                  height        3           0.001
26                   waist        4           0.001

In [1]:
import pandas as pd
df = pd.read_csv('/Users/changsun/GoogleDrive/VWData P8/Infrastructure/Infra_Installation/DataSharing/TSE/TSEDockerFiles_test/output/basic_Dist.csv')
df.columns[400:403]

FileNotFoundError: [Errno 2] File /Users/changsun/GoogleDrive/VWData P8/Infrastructure/Infra_Installation/DataSharing/TSE/TSEDockerFiles_test/output/basic_Dist.csv does not exist: '/Users/changsun/GoogleDrive/VWData P8/Infrastructure/Infra_Installation/DataSharing/TSE/TSEDockerFiles_test/output/basic_Dist.csv'

In [6]:
df[df.columns[400:404]]

,ZVWKPARAMEDISCH_2016_0_pdf,ZVWKHULPMIDDEL_2016_0_hist,ZVWKHULPMIDDEL_2016_0_edges,ZVWKHULPMIDDEL_2016_0_x
0,2.869e-05,0.000116635,0,0
1,2.87893e-05,1.39725e-05,7233.4,22.0935
2,2.88884e-05,4.01024e-06,14466.8,44.1869
3,2.89875e-05,1.9418e-06,21700.2,66.2804
4,2.90864e-05,1.05533e-06,28933.6,88.3738
5,2.91853e-05,5.06556e-07,36167,110.467
6,2.9284e-05,0,43400.4,132.561
7,2.93827e-05,4.2213e-08,50633.8,154.654
8,2.94812e-05,0,57867.2,176.748
9,2.95796e-05,8.4426e-08,65100.6,198.841
10,2.96779e-05,NaN,72334,220.935
11,2.97761e-05,NaN,NaN,243.028
12,2.98741e-05,NaN,NaN,265.121
13,2.9972e-05,NaN,NaN,287.215
14,3.00698e-05,NaN,NaN,309.308
15,3.01675e-05,NaN,NaN,331.402
16,3.0265e-05,NaN,NaN,353.495
17,3.03623e-05,NaN,NaN,375.589
18,3.04596e-05,NaN,NaN,397.682
19,3.05566e-05,NaN,NaN,419.776
20,3.06536e-05,NaN,NaN,441.869
21,3.07503e-05,NaN,NaN,463.962
22,3.08469e-05,NaN,NaN,486.056
23,3.09434e-05,NaN,NaN,508.149
24,3.10397e-05,NaN,NaN,530.243
25,3.11358e-05,NaN,NaN,552.336
26,3.12317e-05,NaN,NaN,574.43
27,3.13275e-05,NaN,NaN,596.523
28,3.14231e-05,NaN,NaN,618.617
29,3.15185e-05,NaN,NaN,640.71
...,...,...,...,...
6521,7.97812e-35,NaN,NaN,71693.2
6522,7.62392e-35,NaN,NaN,71715.3
6523,7.28533e-35,NaN,NaN,71737.4
6524,6.96167e-35,NaN,NaN,71759.5
6525,6.6523e-35,NaN,NaN,71781.6
6526,6.35657e-35,NaN,NaN,71803.7
6527,6.07391e-35,NaN,NaN,71825.8
6528,5.80372e-35,NaN,NaN,71847.9
6529,5.54547e-35,NaN,NaN,71870
6530,5.29863e-35,NaN,NaN,71892.1
6531,5.0627e-35,NaN,NaN,71914.2
6532,4.8372e-35,NaN,NaN,71936.3
6533,4.62168e-35,NaN,NaN,71958.4
6534,4.4157e-35,NaN,NaN,71980.5
6535,4.21883e-35,NaN,NaN,72002.6
6536,4.03067e-35,NaN,NaN,72024.7
6537,3.85086e-35,NaN,NaN,72046.7
6538,3.679e-35,NaN,NaN,72068.8
6539,3.51477e-35,NaN,NaN,72090.9
6540,3.35781e-35,NaN,NaN,72113
6541,3.20782e-35,NaN,NaN,72135.1
6542,3.06448e-35,NaN,NaN,72157.2
6543,2.9275e-35,NaN,NaN,72179.3
6544,2.7966e-35,NaN,NaN,72201.4
6545,2.67152e-35,NaN,NaN,72223.5
6546,2.55199e-35,NaN,NaN,72245.6
6547,2.43777e-35,NaN,NaN,72267.7
6548,2.32863e-35,NaN,NaN,72289.8
6549,2.22434e-35,NaN,NaN,72311.9
6550,2.12469e-35,NaN,NaN,72334

In [3]:
df1=pd.read_csv('/Users/changsun/GoogleDrive/VWData P8/Infrastructure/Infra_Installation/DataSharing/TSE/TSEDockerFiles_test/output/basic_describe.csv')
len(df1.columns)

122