In [180]:
import pandas as pd
import pyreadstat

In [181]:
### remove unnecessary columns ###
### Set "encString" as index ###

In [182]:
df = pd.read_csv('query-result.csv')
df_V1 = df.drop(['encTableRow','myRandomDouble','myRandomInt','dataTableRow'],axis=1)
df_V1 = df_V1.set_index('encString')
df_col = df_V1.columns
# df_V1

In [183]:
# from os import path
# test=df_V1[['SEX','Age']].iloc[0:5]

# outputFile="test.csv"
# if path.exists(outputFile) == False:
#     with open(outputFile, 'w') as f:
#         test.to_csv(f)
# if path.exists(outputFile) == True:
#     with open(outputFile, 'a') as f:
#         test.to_csv(f)

In [184]:
### variable value to labels ###

In [185]:
df_ori, meta = pyreadstat.read_sav('AV291v3.sav')

In [186]:
value_labels = meta.variable_value_labels
for c in df_col:
    if c in value_labels:
        if c != 'NIT_kcal' and c != 'medGRscore_TR':
            print(c)
            if c == 'n_smokingcat4':
                temp = {0.0: 'never', 1.0: 'former &gt;6mnd', 2.0: 'former &lt;6mnd', 3.0: 'current'}
                new_dict = dict([(value, key) for key, value in temp.items()]) 
                df_V1 = df_V1.replace({c: new_dict})
                
            elif c == 'N_ALCOHOL_CAT':
                temp = {0.0: 'None', 1.0: 'Low (women:&lt;=7; men:&lt;=14)', 2.0: 'High (women&gt;7; men&gt;14)'}
                new_dict = dict([(value, key) for key, value in temp.items()]) 
                df_V1 = df_V1.replace({c: new_dict})
                
            else:
                new_dict = dict([(value, key) for key, value in value_labels[c].items()]) 
                df_V1 = df_V1.replace({c: new_dict})

N_GTS_WHO
N_Diabetes_WHO_2
N_DIABETES_2
N_T2DM_new_diagn
SEX
N_Education_3cat
Employment_status
Occupational_category
n_smokingcat4
N_ALCOHOL_CAT
N_CVD
med_depression
PHQ9_depr
MINIcurrdepr
MINIlifedepr
N_HT
SF36_Q7
SF36_Q10

In [187]:
# df_V1["VISIT1_DATE"] = list(df_ori.VISIT1_DATE)
len(df_ori)

3285

In [188]:
df_V1 = df_V1.drop("VISIT1_DATE",axis=1)
df_V1

,N_DM_DUR_2,N_GTS_WHO,N_Diabetes_WHO_2,N_DIABETES_2,N_T2DM_new_diagn,SEX,Age,N_Education_3cat,Employment_status,Occupational_category,...,TOTALPA,MVPA,MEAN_VALID_MIN_SLEEP_T,MEAN_SED_MIN_WAKE_T,MEAN_STAND_MIN_WAKE_T,MEAN_STEP_MIN_WAKE_T,waist,hip,SF36_Q7,SF36_Q10
encString,,,,,,,,,,,,,,,,,,,,,
b'bae6fb057d8eb3d5d9154166075e7f4d675535be3544f32520f8e57707ff9cdd0d3e7957de8d6674318a666b347caa84eaf5b596b0a2483e9d6b57bdb3b30dab',NaN,4.0,3.0,NaN,NaN,2.0,54,1.0,NaN,NaN,...,NaN,NaN,410.488571,730.735001,204.387619,92.290952,96.70,102.90,3.0,3.0
b'776d7b46192d6b6872585a49eaa1239ee05b438d1704dd97de580c10207336ab0aa57749a52345f612a33b0e1550e4e2248ed87466de37fa338cd5f69a50abb9',NaN,0.0,0.0,0.0,0.0,2.0,46,2.0,1.0,NaN,...,20.50,11.75,501.579762,566.280834,255.205833,110.210001,82.75,100.15,3.0,3.0
b'e7d2e176a2ed495c83bb9ac109041f358dee6c95d36b6da298009174198424ade5b368615ff7ed8a468dda4da58899b3e44269cfbd6f69fc4a113fd1efeb4cb1',NaN,3.0,2.0,1.0,1.0,1.0,69,1.0,NaN,NaN,...,NaN,NaN,599.860833,694.905556,112.192500,40.012778,99.50,97.50,3.0,3.0
b'9ec0b3e1edfe87159a8e01bd0f21fec91a2e9777a61026d2a18f4a412b260b34b449922d640530919606ea54f32c9157bccee0100b8242f613bda42f94961cc4',NaN,3.0,2.0,1.0,1.0,1.0,68,2.0,0.0,0.0,...,11.00,1.50,483.853333,714.704286,183.267143,60.901190,129.75,129.50,3.0,3.0
b'4e55023b2e8e289e13d04b500d94f06b738b30658f04092c4f58bc63bf2729b6c1aa5253e890061b58a1d9ff2af1488caac21a384798e8fcd3c57dc1be51ad18',NaN,0.0,0.0,0.0,0.0,2.0,46,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,75.50,89.00,3.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
b'd93c39cbb81484f63b5fc79b15928e2ccd6109319fad5b438f692aac7438d7dc82b52e1d212ad935168f0f5786ad60b80127f4f28f6b804d1dcaaff3675d6046',NaN,0.0,0.0,0.0,0.0,1.0,64,1.0,0.0,0.0,...,12.25,1.50,517.807619,384.770000,451.918809,83.679524,104.75,104.85,2.0,2.0
b'72f193d3005666fbf41e228dc15dcb3f70be13b47de16e0f90524f11df1a1bb992ec71601def893687a42264f083f14b3c23c30188e5df063fd6209ca132fb4c',NaN,0.0,0.0,0.0,0.0,2.0,55,3.0,1.0,3.0,...,26.50,19.00,NaN,NaN,NaN,NaN,91.00,101.00,3.0,3.0
b'ee04cabc38c4d58877b42e079dbb7dd5f570b37189bdae9a1b7037ac9e60439b139418ef82bef8f15c547029e8164e1cad072cab533ae64a42c4b6919312b031',NaN,0.0,0.0,0.0,0.0,1.0,49,2.0,1.0,3.0,...,NaN,NaN,539.321333,472.990667,272.268333,147.196334,96.05,102.85,3.0,3.0
b'008ff9224b771e2919e68d4886e8dcdd05c8f45e2679d4dc8fd3870c982781c2e35a496936959c8eafac24c5c6fc38e478f1444455dabc851062f53d3c9c8bf9',2.0,3.0,2.0,1.0,1.0,2.0,58,1.0,0.0,0.0,...,8.00,3.00,494.873095,457.551111,369.867778,131.561945,104.00,105.00,3.0,3.0
b'23e4602114fcb97f2fec11cf6c0230bb2e28ad9316ec5829df38fa3785088cd9cf797db9fd68f47c34e4e32e555707243fd9c7d53241bdf39fa513f3cd3727b8',NaN,0.0,0.0,0.0,0.0,1.0,49,2.0,1.0,1.0,...,8.25,0.75,506.519524,588.116943,267.449167,86.744167,110.50,102.50,2.0,2.0

In [189]:
df_V1.to_csv('20200309_edited_result.csv')
pd.read_csv('20200309_edited_result.csv').dtypes

encString                  object
N_DM_DUR_2                float64
N_GTS_WHO                 float64
N_Diabetes_WHO_2          float64
N_DIABETES_2              float64
N_T2DM_new_diagn          float64
SEX                       float64
Age                         int64
N_Education_3cat          float64
Employment_status         float64
Occupational_category     float64
Income_equivalent         float64
n_smokingcat4             float64
WOZ                       float64
N_ALCOHOL_CAT             float64
NIT_kcal                  float64
medGRscore_TR             float64
height                    float64
weight                    float64
bmi                       float64
N_CVD                     float64
med_depression            float64
PHQ9_depr                 float64
MINIcurrdepr              float64
MINIlifedepr              float64
N_HT                      float64
TOTALPA                   float64
MVPA                      float64
MEAN_VALID_MIN_SLEEP_T    float64
MEAN_SED_MIN_WAKE_T       float64
MEAN_STAND_MIN_WAKE_T     float64
MEAN_STEP_MIN_WAKE_T      float64
waist                     float64
hip                       float64
SF36_Q7                   float64
SF36_Q10                  float64
dtype: object

In [190]:
# df_2 = pd.read_csv('query-result.csv', index_col='encString')

In [191]:
df_make = df_ori.reset_index()
df_make = df_make.drop([236])
df_make = df_make.reset_index()
df_make = df_make.drop(['level_0','index','RandomID'],axis=1)
df_make_2 = df_make.drop([426])#.iloc[420:430]
df_make_2 = df_make_2.reset_index()

In [192]:
df_make_2

,index,N_DM_DUR_2,N_GTS_WHO,N_Diabetes_WHO_2,N_DIABETES_2,N_T2DM_new_diagn,SEX,Age,N_Education_3cat,Employment_status,...,MEAN_VALID_MIN_WAKE_T,MEAN_VALID_MIN_SLEEP_T,MEAN_SED_MIN_WAKE_T,MEAN_STAND_MIN_WAKE_T,PROP_STAND_MIN_WAKE_T,MEAN_STEP_MIN_WAKE_T,VISIT1_DATE,waist,hip,Mobility_lim
0,0,NaN,4.0,3.0,NaN,NaN,2.0,54.0,1.0,NaN,...,1027.414286,410.488571,730.735000,204.387619,19.893399,92.290952,2013-01-07,96.70,102.90,0.0
1,1,NaN,0.0,0.0,0.0,0.0,2.0,46.0,2.0,1.0,...,931.698611,501.579762,566.280833,255.205833,27.391458,110.210000,2012-07-25,82.75,100.15,0.0
2,2,NaN,3.0,2.0,1.0,1.0,1.0,69.0,1.0,NaN,...,847.110833,599.860833,694.905556,112.192500,13.244135,40.012778,2011-12-23,99.50,97.50,0.0
3,3,NaN,3.0,2.0,1.0,1.0,1.0,68.0,2.0,0.0,...,958.874048,483.853333,714.704286,183.267143,19.112744,60.901190,2012-09-06,129.75,129.50,0.0
4,4,NaN,0.0,0.0,0.0,0.0,2.0,46.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2011-08-18,75.50,89.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3278,3279,NaN,0.0,0.0,0.0,0.0,1.0,64.0,1.0,0.0,...,920.375952,517.807619,384.770000,451.916429,49.101286,83.679524,2012-12-20,104.75,104.85,1.0
3279,3280,NaN,0.0,0.0,0.0,0.0,2.0,55.0,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2011-01-21,91.00,101.00,0.0
3280,3281,NaN,0.0,0.0,0.0,0.0,1.0,49.0,2.0,1.0,...,892.455333,539.321333,472.990667,272.268333,30.507783,147.196333,2013-01-18,96.05,102.85,0.0
3281,3282,2.0,3.0,2.0,1.0,1.0,2.0,58.0,1.0,0.0,...,958.980833,492.536389,457.551111,369.867778,38.568839,131.561944,2012-03-14,104.00,105.00,0.0
3282,3283,NaN,0.0,0.0,0.0,0.0,1.0,49.0,2.0,1.0,...,942.312222,481.706944,588.116944,267.449167,28.382224,86.744167,2012-05-07,110.50,102.50,1.0

In [193]:
for i in range(0, len(df_V1)):
    if round(df_V1['height'][i],7) != round(df_make_2['height'][i],7):
        print(i, df_V1['height'][i], df_make_2['height'][i])

533 nan nan
845 nan nan
3017 nan nan

In [198]:
df_V1['VISIT1_DATE'] = list(df_make_2['VISIT1_DATE'])
df_V1['Mobility_lim'] = list(df_make_2['Mobility_lim'])

In [200]:
df_V1
# Save with encString ##
df_V1.to_csv('20200309_edited_result.csv')

In [201]:
df_V1_reindex = df_V1.reset_index()
df_V1_reindex = df_V1_reindex.drop('encString', axis=1)
df_V1_reindex

,N_DM_DUR_2,N_GTS_WHO,N_Diabetes_WHO_2,N_DIABETES_2,N_T2DM_new_diagn,SEX,Age,N_Education_3cat,Employment_status,Occupational_category,...,MEAN_VALID_MIN_SLEEP_T,MEAN_SED_MIN_WAKE_T,MEAN_STAND_MIN_WAKE_T,MEAN_STEP_MIN_WAKE_T,waist,hip,SF36_Q7,SF36_Q10,VISIT1_DATE,Mobility_lim
0,NaN,4.0,3.0,NaN,NaN,2.0,54,1.0,NaN,NaN,...,410.488571,730.735001,204.387619,92.290952,96.70,102.90,3.0,3.0,2013-01-07,0.0
1,NaN,0.0,0.0,0.0,0.0,2.0,46,2.0,1.0,NaN,...,501.579762,566.280834,255.205833,110.210001,82.75,100.15,3.0,3.0,2012-07-25,0.0
2,NaN,3.0,2.0,1.0,1.0,1.0,69,1.0,NaN,NaN,...,599.860833,694.905556,112.192500,40.012778,99.50,97.50,3.0,3.0,2011-12-23,0.0
3,NaN,3.0,2.0,1.0,1.0,1.0,68,2.0,0.0,0.0,...,483.853333,714.704286,183.267143,60.901190,129.75,129.50,3.0,3.0,2012-09-06,0.0
4,NaN,0.0,0.0,0.0,0.0,2.0,46,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,75.50,89.00,3.0,3.0,2011-08-18,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3278,NaN,0.0,0.0,0.0,0.0,1.0,64,1.0,0.0,0.0,...,517.807619,384.770000,451.918809,83.679524,104.75,104.85,2.0,2.0,2012-12-20,1.0
3279,NaN,0.0,0.0,0.0,0.0,2.0,55,3.0,1.0,3.0,...,NaN,NaN,NaN,NaN,91.00,101.00,3.0,3.0,2011-01-21,0.0
3280,NaN,0.0,0.0,0.0,0.0,1.0,49,2.0,1.0,3.0,...,539.321333,472.990667,272.268333,147.196334,96.05,102.85,3.0,3.0,2013-01-18,0.0
3281,2.0,3.0,2.0,1.0,1.0,2.0,58,1.0,0.0,0.0,...,494.873095,457.551111,369.867778,131.561945,104.00,105.00,3.0,3.0,2012-03-14,0.0
3282,NaN,0.0,0.0,0.0,0.0,1.0,49,2.0,1.0,1.0,...,506.519524,588.116943,267.449167,86.744167,110.50,102.50,2.0,2.0,2012-05-07,1.0

In [202]:
cbs_data = pd.read_csv('CBSTestingData.csv')
df_V1_reindex['GBAGeboorteJaar'] = cbs_data['GBAGeboorteJaar']
df_V1_reindex['GBAGeboorteMaand'] = cbs_data['GBAGeboorteMaand']
df_V1_reindex['GBAGeboorteDag'] = cbs_data['GBAGeboorteDag']
df_V1_reindex['GBAGeslacht'] = cbs_data['GBAGeslacht']
df_V1_reindex['GBAPostcode'] = cbs_data['GBAPostcode']
df_V1_reindex['GBAHuisnummer'] = cbs_data['GBAHuisnummer']
df_V1_reindex['GBAToev'] = cbs_data['GBAToev']

In [204]:
df_V1_reindex.to_csv("20200309_dms.csv")

In [203]:
df_V1_reindex

,N_DM_DUR_2,N_GTS_WHO,N_Diabetes_WHO_2,N_DIABETES_2,N_T2DM_new_diagn,SEX,Age,N_Education_3cat,Employment_status,Occupational_category,...,SF36_Q10,VISIT1_DATE,Mobility_lim,GBAGeboorteJaar,GBAGeboorteMaand,GBAGeboorteDag,GBAGeslacht,GBAPostcode,GBAHuisnummer,GBAToev
0,NaN,4.0,3.0,NaN,NaN,2.0,54,1.0,NaN,NaN,...,3.0,2013-01-07,0.0,1916,4,17,0,8275 QI,97,I
1,NaN,0.0,0.0,0.0,0.0,2.0,46,2.0,1.0,NaN,...,3.0,2012-07-25,0.0,1904,12,3,0,6892 ZT,0,T
2,NaN,3.0,2.0,1.0,1.0,1.0,69,1.0,NaN,NaN,...,3.0,2011-12-23,0.0,1906,9,2,1,3707 PZ,84,Z
3,NaN,3.0,2.0,1.0,1.0,1.0,68,2.0,0.0,0.0,...,3.0,2012-09-06,0.0,1993,12,6,1,6570 WP,9,P
4,NaN,0.0,0.0,0.0,0.0,2.0,46,2.0,NaN,NaN,...,3.0,2011-08-18,0.0,1940,12,4,0,4799TF,9,F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3278,NaN,0.0,0.0,0.0,0.0,1.0,64,1.0,0.0,0.0,...,2.0,2012-12-20,1.0,1904,6,25,0,4585LA,0,A
3279,NaN,0.0,0.0,0.0,0.0,2.0,55,3.0,1.0,3.0,...,3.0,2011-01-21,0.0,2011,9,28,1,2959 PC,66,C
3280,NaN,0.0,0.0,0.0,0.0,1.0,49,2.0,1.0,3.0,...,3.0,2013-01-18,0.0,1996,5,4,1,7611 QT,891,T
3281,2.0,3.0,2.0,1.0,1.0,2.0,58,1.0,0.0,0.0,...,3.0,2012-03-14,0.0,1939,12,30,1,6722 QG,809,G
3282,NaN,0.0,0.0,0.0,0.0,1.0,49,2.0,1.0,1.0,...,2.0,2012-05-07,1.0,1972,10,4,1,9377 CY,82,Y

In [106]:
cbs_data = pd.read_csv('CBSTestingData.csv')
cbs_data = cbs_data.drop(['GBAGeboorteJaar', 'GBAGeboorteMaand', 'GBAGeboorteDag',\
                         'GBAGeslacht', 'GBAPostcode', 'GBAHuisnummer', 'GBAToev'], axis=1)

In [120]:
cbs_data['encString'] = (list(df_V1.index) + list(cbs_data.index[3283:5000]))
cbs_data = cbs_data.set_index('encString')

In [127]:
cbs_data.to_csv('20200308_cbs.csv')

,ZVWKOPHOOGFACTOR_2010,ZVWKHUISARTS_2010,ZVWKFARMACIE_2010,ZVWKZIEKENHUIS_2010,ZVWKPARAMEDISCH_2010,ZVWKHULPMIDDEL_2010,ZVWKZIEKENVERVOER_2010,ZVWKBUITENLAND_2010,ZVWKOVERIG_2010,ZVWKEERSTELIJNSPSYCHO_2010,...,ZVWKPARAMEDISCH_2016,ZVWKHULPMIDDEL_2016,ZVWKZIEKENVERVOER_2016,ZVWKBUITENLAND_2016,ZVWKOVERIG_2016,ZVWKEERSTELIJNSPSYCHO_2016,ZVWKGGZ_2016,ZVWKGERIATRISCH_2016,ZVWKWYKVERPLEGING_2016,ZVWKMULTIDISC_2016
encString,,,,,,,,,,,,,,,,,,,,,
b'bae6fb057d8eb3d5d9154166075e7f4d675535be3544f32520f8e57707ff9cdd0d3e7957de8d6674318a666b347caa84eaf5b596b0a2483e9d6b57bdb3b30dab',0,4910.70,10038.97,556937.65,10765.74,3076.54,0.00,55894.77,147.31,30.43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
b'776d7b46192d6b6872585a49eaa1239ee05b438d1704dd97de580c10207336ab0aa57749a52345f612a33b0e1550e4e2248ed87466de37fa338cd5f69a50abb9',0,13054.55,27792.88,1429760.50,11037.51,4713.04,0.00,10487.59,663.95,1.88,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
b'e7d2e176a2ed495c83bb9ac109041f358dee6c95d36b6da298009174198424ade5b368615ff7ed8a468dda4da58899b3e44269cfbd6f69fc4a113fd1efeb4cb1',0,6876.96,27905.14,1024430.14,4322.06,6020.77,0.00,4027.32,124.89,3.45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
b'9ec0b3e1edfe87159a8e01bd0f21fec91a2e9777a61026d2a18f4a412b260b34b449922d640530919606ea54f32c9157bccee0100b8242f613bda42f94961cc4',0,6717.20,9233.62,654305.31,4099.72,8907.87,0.00,134264.00,434.36,0.31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
b'4e55023b2e8e289e13d04b500d94f06b738b30658f04092c4f58bc63bf2729b6c1aa5253e890061b58a1d9ff2af1488caac21a384798e8fcd3c57dc1be51ad18',0,18455.48,71305.59,3099725.28,14899.78,9494.83,0.00,18783.04,4635.02,7.85,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,0,1691.68,3820.92,35508.52,5008.38,3309.67,5225.42,218.44,43.42,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4996,0,9766.97,42881.75,231352.46,5564.28,1545.28,3279.76,217.08,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4997,0,1757.01,2756.42,51663.85,1393.39,8841.25,0.00,176.54,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4998,0,1731.44,4274.98,32289.36,9539.99,21465.06,0.00,2440.30,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4999,0,1916.74,6689.37,26232.63,561.49,1.36,0.00,132.74,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# df_oops = df_make_2.drop('index',axis=1)
# df_oops.index = df_2.index
# df_oops.to_csv('dms_noSuffix.csv')

In [ ]:
# df_t1 = pd.read_csv('dms_withSuffix.csv')
# df_t2 = pd.read_csv('dms_noSuffix.csv')

# cnt = 0
# for i in range(0,len(df_t1)):
#     if df_t1['encString'][i] != df_t2['encString'][i]:
#         cnt = cnt + 1
# print(cnt)

In [ ]:
# df_1 = pd.read_csv('20191030_edited_result.csv')
# df_2 = pd.read_csv('query-result.csv')

In [ ]:
# withSuf = []
# noSuf = []
# for i in range(0, len(df_1)):
#     if df_1['encString'][i] == df_2['encString'][i]:
#         noSuf.append(i)
#     else:
#         withSuf.append(i)

In [ ]:
# noSuf_df = df_1.iloc[noSuf][['SEX','Age']]
# noSuf_df.index = df_1.iloc[noSuf]['encString']
# noSuf_df.to_csv('dms_noSuffix.csv')

In [ ]:
# withSuf_df = df_1.iloc[withSuf][['SEX','Age']]
# withSuf_df.index = df_1.iloc[withSuf]['encString']
# withSuf_df.to_csv('dms_withSuffix.csv')

In [ ]:
# import numpy as np
# hist, edges = np.histogram(df_1['Age'], density=True)

In [ ]:
# df_1.describe().to_csv('test.csv')

In [ ]:
##### 2019-11-09 New Suffix info #####

In [2]:
# df = pd.read_csv('201911/20191109_query_result.csv')
# df_V1 = df.drop(['encTableRow','myRandomDouble','myRandomInt','dataTableRow'],axis=1)
# onlyEnc_1 = df_V1['encString']
# df_V1 = df_V1.set_index('encString')
# # df_col = df_V1.columns
# # df_V1

In [3]:
# pre_df = pd.read_csv('201910/20191030_edited_result.csv')
# onlyEnc_0 = pre_df['encString']
# df_temp = pre_df.drop('encString',axis=1)

In [4]:
# cnt = []
# for i in range(0,len(onlyEnc_0)):
#     if onlyEnc_0[i] != onlyEnc_1[i]:
#         cnt.append(i)
# print(len(cnt))

759

In [7]:
# # pd.DataFrame.from_records(onlyEnc_1)
# new_df = pd.concat([onlyEnc_1,df_temp],axis=1,join='inner')
# new_df = new_df.set_index('encString')
# # save_df = new_df.iloc[cnt]
# save_df = save_df.set_index('encString')
# save_df.to_csv('20191109_pureSuffix_result.csv')

# all (new_df.index == onlyEnc_1)

In [50]:
# !pip install pyreadstat